server:
  port: 8081

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5433/adikabuyer
    username: adikabuyer
    password: adikabuyer
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  rabbitmq:
    host: localhost
    port: 5672
    username: adikabuyer
    password: adikabuyer
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  s3:
    access-key: ${S3_ACCESS_KEY:adikabuyer}
    secret-key: ${S3_SECRET_KEY:adikabuyer123}
    bucket: ${S3_BUCKET:adikabuyer-media}
    endpoint: ${S3_ENDPOINT:http://localhost:9000}
    region: ${S3_REGION:auto}
    public-url-base: ${S3_PUBLIC_URL_BASE:http://localhost:9000/adikabuyer-media}
  rabbitmq:
    exchange: order.exchange
    queue: order.queue
    routing-key: order.new
  jwt:
    secret: "3f8a1c9d4b7e2f6a8c1d5e9f3a7b2c6d8e1f4a9c3b7d2e6f8a1c4d9e3b7f2a6c"
    expiration-ms: 3600000
  security:
    admin-username: admin
    admin-password-hash: "$2a$10$lCNeUqJeSoXyb6k4Mh6lLe.hWP9dJ0aVqFVwp9GyjjN0B4s3KJV32"
