services:
  postgres-db:
    image: postgres:16-alpine
    container_name: adikabuyer-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: adikabuyer
      POSTGRES_PASSWORD: adikabuyer
      POSTGRES_DB: adikabuyer
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - adikabuyer-network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: adikabuyer-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: adikabuyer
      RABBITMQ_DEFAULT_PASS: adikabuyer
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - adikabuyer-network

  api-gateway:
    build:
      context: ./api-gateway
    container_name: adikabuyer-api-gateway
    restart: unless-stopped
    environment:
      CATALOG_SERVICE_URL: http://host.docker.internal:8081
      ORDER_SERVICE_URL: http://host.docker.internal:8082
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - adikabuyer-network

networks:
  adikabuyer-network:
    driver: bridge

volumes:
  postgres-data:
  rabbitmq-data:
