package com.adikabuyer.order.telegram;

import com.adikabuyer.order.dto.CartDto;
import com.adikabuyer.order.dto.CartItemDto;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

class OrderNotificationMessageBuilderTest {

    private CartItemDto buildItem(BigDecimal unitPrice, int quantity) {
        return new CartItemDto(
                1L,
                "Custom Tumbler",
                "TUM-BLK-500",
                Map.of("color", "black", "size", "500ml"),
                unitPrice,
                quantity
        );
    }

    private CartDto buildCart(String region, CartItemDto... items) {
        return new CartDto("John Doe", "996700123456", region, List.of(items));
    }

    @Test
    void buildOrderMessage_includesCustomerDetailsAndItemLines() {
        CartDto cart = buildCart("Ош", buildItem(BigDecimal.valueOf(25), 2));

        String message = OrderNotificationMessageBuilder.buildOrderMessage(
                "order-1", cart, BigDecimal.valueOf(50), BigDecimal.valueOf(500), BigDecimal.valueOf(550)
        );

        assertThat(message)
                .contains("Имя: John Doe")
                .contains("Телефон: 996700123456")
                .contains("Город: Ош")
                .contains("2x Custom Tumbler (black, 500ml, TUM-BLK-500) — 50 KGS")
                .contains("Товары: 50 KGS")
                .contains("Доставка: 500 KGS")
                .contains("Итого: 550 KGS");
    }

    @Test
    void buildOrderMessage_formatsLargeTotals_withGroupedDigitsAndNoKopecks() {
        CartDto cart = buildCart("Ош", buildItem(BigDecimal.valueOf(2200.50), 5));

        String message = OrderNotificationMessageBuilder.buildOrderMessage(
                "order-1", cart, BigDecimal.valueOf(11002.50), BigDecimal.valueOf(500), BigDecimal.valueOf(11502.50)
        );

        assertThat(message)
                .contains("Товары: 11 003 KGS")
                .contains("Итого: 11 503 KGS");
    }

    @Test
    void buildOrderMessage_omitsAutoGeneratedSku() {
        CartItemDto item = new CartItemDto(1L, "Предмет", "DEFAULT-8C54E689", Map.of(), BigDecimal.valueOf(2200), 1);
        CartDto cart = buildCart("Бишкек", item);

        String message = OrderNotificationMessageBuilder.buildOrderMessage(
                "order-1", cart, BigDecimal.valueOf(2200), BigDecimal.valueOf(250), BigDecimal.valueOf(2450)
        );

        assertThat(message)
                .contains("1x Предмет — 2 200 KGS")
                .doesNotContain("DEFAULT-");
    }

    @Test
    void buildOrderMessage_keepsHostileCustomerNameVerbatim() {
        CartDto cart = new CartDto(
                "Robert'); DROP TABLE orders;-- <script>alert(1)</script>",
                "996700123456",
                "Ош",
                List.of(buildItem(BigDecimal.TEN, 1))
        );

        String message = OrderNotificationMessageBuilder.buildOrderMessage(
                "order-1", cart, BigDecimal.TEN, BigDecimal.ZERO, BigDecimal.TEN
        );

        assertThat(message).contains("<script>alert(1)</script>");
    }

    @Test
    void buildOrderMessage_joinsMultipleItemLines() {
        CartItemDto first = buildItem(BigDecimal.valueOf(10), 2);
        CartItemDto second = new CartItemDto(2L, "Gym Shorts", "GYM-BLK-M", Map.of("size", "M"), BigDecimal.valueOf(15), 3);
        CartDto cart = buildCart("Ош", first, second);

        String message = OrderNotificationMessageBuilder.buildOrderMessage(
                "order-1", cart, BigDecimal.valueOf(65), BigDecimal.ZERO, BigDecimal.valueOf(65)
        );

        assertThat(message)
                .contains("2x Custom Tumbler (black, 500ml, TUM-BLK-500) — 20 KGS")
                .contains("3x Gym Shorts (M, GYM-BLK-M) — 45 KGS");
    }
}
